# Generated by Django 5.2.4 on 2025-07-12 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_customuser_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_feedposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
